server:
  port: 8087

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/sparta
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none

    show-sql: true

    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true
    locations: classpath:db/migration

  # Spring AI
  ai:
    openai:
      api-key: ${GEMINI_API_KEY}

      base-url: https://generativelanguage.googleapis.com/v1beta/openai

      chat:
        completions-path: /chat/completions

        options:
          model: gemini-3.5-flash-lite
          temperature: 0.7
          max-tokens: 4096

    vectorstore:
      pgvector:
        # Flyway에서 직접 vector_store 테이블을 생성하므로 false
        initialize-schema: false

        # 임베딩 Vector 차원
        dimensions: 3072

        # Vector 유사도 계산 방법
        distance-type: COSINE_DISTANCE

        # Vector 검색 인덱스
        index-type: HNSW

logging:
  level:
    org.hibernate.SQL: DEBUG