CREATE TABLE chat_conversations
(
    id UUID PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE chat_messages
(
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- 어떤 채팅방의 메시지인지
    conversation_id UUID NOT NULL,

    -- USER / ASSISTANT / SYSTEM / SUMMARY
    role VARCHAR(20) NOT NULL,

    -- ACTIVE / INACTIVE / DELETED
    status VARCHAR(20) NOT NULL,

    -- 실제 대화 내용
    message TEXT NOT NULL,

    -- AI 호출 시 사용된 Token 정보
    prompt_tokens INTEGER,
    completion_tokens INTEGER,
    total_tokens INTEGER,

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    -- ChatConversation과의 FK 관계
    CONSTRAINT fk_chat_messages_conversation
        FOREIGN KEY (conversation_id)
        REFERENCES chat_conversations(id)
);